application:
  title: @project.name@
  version: @project.version@

---
spring:
  config:
    activate:
      on-profile:
        - prod

server:
  port: 8090
---
spring:
  config:
    activate:
      on-profile:
        - vorprod
key: value